services:
  - type: web
    name: ronniEbook-other-services
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 run_prod.py"
    plan: free 
    region: singapore
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
